output "resource_group_name" {
  description = "Resource group created for the AKS platform."
  value       = module.resource_group.name
}

output "location" {
  description = "Azure location in use."
  value       = module.resource_group.location
}

output "aks_name" {
  description = "AKS cluster name."
  value       = module.aks.name
}

output "aks_id" {
  description = "AKS cluster resource ID."
  value       = module.aks.id
}

output "aks_fqdn" {
  description = "AKS API server FQDN."
  value       = module.aks.fqdn
}

output "aks_oidc_issuer_url" {
  description = "OIDC issuer URL used by workload identity."
  value       = module.aks.oidc_issuer_url
}

output "aks_node_resource_group" {
  description = "Node resource group generated by AKS."
  value       = module.aks.node_resource_group
}

output "acr_name" {
  description = "Azure Container Registry name."
  value       = module.acr.name
}

output "acr_login_server" {
  description = "ACR login server endpoint."
  value       = module.acr.login_server
}

output "vnet_name" {
  description = "Virtual network name."
  value       = module.network.vnet_name
}

output "aks_subnet_id" {
  description = "Subnet ID used by AKS."
  value       = module.network.subnet_id
}
